/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stock.market.simulator;

import stock.controller.*;
import stock.model.*;
import stock.view.*;



import org.junit.Test;
import stock.App;

import static org.junit.Assert.*;

public class StockMarketTest {
    @Test public void playerCapital() {
       User player = new User(100);
       player.setCapital(275.00f);
        
       if 
       assertArrayEquals(float:275.00f, )
      
    }

    @Test public void patternAfterGuesses() {
      
    }
}
